name: fastbook_voila
channels:
    - fastai
    - pytorch
    - defaults
dependencies:
  - python>=3.6
  - pytorch<2.7,>=1.10
  - torchvision
  - torchaudio
  - pip
  - fastai
  - fastbook
  - pip:
    - pexels-api-py
    - -r requirements.txt